services:
  mysql_db:
    image: mysql:8.0 # You can choose a different version if needed
    container_name: my_mysql_two_dbs
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ordersdb # This will create the first database
    ports:
      - "3307:3306" # Maps host port 3307 to container port 3306
    volumes:
      - db_data:/var/lib/mysql # Persist data to a named volume
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql # Custom init script
    command: --default-authentication-plugin=mysql_native_password # Recommended for newer MySQL versions
    healthcheck: # Optional: Basic health check for the database
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pexample"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: