# Generated by Django 3.2.25 on 2025-06-26 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimCustomer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('segment', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dimension Customer',
                'verbose_name_plural': 'Dimension Customers',
                'db_table': 'dim_customer',
            },
        ),
        migrations.CreateModel(
            name='DimDate',
            fields=[
                ('date_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_date', models.DateField(unique=True)),
                ('day_of_week', models.CharField(max_length=20)),
                ('month_name', models.CharField(max_length=20)),
                ('quarter', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Dimension Date',
                'verbose_name_plural': 'Dimension Dates',
                'db_table': 'dim_date',
            },
        ),
        migrations.CreateModel(
            name='DimDeliveryPerson',
            fields=[
                ('delivery_person_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_person_name', models.CharField(blank=True, max_length=255, null=True)),
                ('operation_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('tenure_months', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dimension Delivery Person',
                'verbose_name_plural': 'Dimension Delivery People',
                'db_table': 'dim_deliveryperson',
            },
        ),
        migrations.CreateModel(
            name='DimLocation',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Dimension Location',
                'verbose_name_plural': 'Dimension Locations',
                'db_table': 'dim_location',
            },
        ),
        migrations.CreateModel(
            name='DimRestaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=255)),
                ('cuisine_type', models.CharField(max_length=100)),
                ('rating_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'verbose_name': 'Dimension Restaurant',
                'verbose_name_plural': 'Dimension Restaurants',
                'db_table': 'dim_restaurant',
                'unique_together': {('restaurant_name', 'cuisine_type')},
            },
        ),
        migrations.CreateModel(
            name='DimTimeSlot',
            fields=[
                ('time_slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_name', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dimension Time Slot',
                'verbose_name_plural': 'Dimension Time Slots',
                'db_table': 'dim_timeslot',
            },
        ),
        migrations.CreateModel(
            name='FactOrders',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('order_time', models.TimeField(blank=True, null=True)),
                ('order_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('food_preparation_time', models.IntegerField(blank=True, null=True)),
                ('delivery_time', models.IntegerField(blank=True, null=True)),
                ('total_time', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='warehouse.dimcustomer')),
                ('date', models.ForeignKey(db_column='date_id', on_delete=django.db.models.deletion.CASCADE, to='warehouse.dimdate')),
                ('delivery_person', models.ForeignKey(blank=True, db_column='delivery_person_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.dimdeliveryperson')),
                ('location', models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.dimlocation')),
                ('restaurant', models.ForeignKey(db_column='restaurant_id', on_delete=django.db.models.deletion.CASCADE, to='warehouse.dimrestaurant')),
                ('time_slot', models.ForeignKey(blank=True, db_column='time_slot_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.dimtimeslot')),
            ],
            options={
                'verbose_name': 'Fact Order',
                'verbose_name_plural': 'Fact Orders',
                'db_table': 'fact_orders',
            },
        ),
    ]
