# Generated by Django 3.2.25 on 2025-06-26 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorders',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='warehouse.dimcustomer'),
        ),
        migrations.AlterField(
            model_name='factorders',
            name='date',
            field=models.ForeignKey(db_column='date_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='warehouse.dimdate'),
        ),
        migrations.AlterField(
            model_name='factorders',
            name='delivery_person',
            field=models.ForeignKey(blank=True, db_column='delivery_person_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='warehouse.dimdeliveryperson'),
        ),
        migrations.AlterField(
            model_name='factorders',
            name='location',
            field=models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='warehouse.dimlocation'),
        ),
        migrations.AlterField(
            model_name='factorders',
            name='restaurant',
            field=models.ForeignKey(db_column='restaurant_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='warehouse.dimrestaurant'),
        ),
        migrations.AlterField(
            model_name='factorders',
            name='time_slot',
            field=models.ForeignKey(blank=True, db_column='time_slot_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='warehouse.dimtimeslot'),
        ),
    ]
