
services:
  webserver:
    image: etl-app
    build: .
    container_name: etl-webserver
    restart: unless-stopped
    init: true
    depends_on:
      - scheduler
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./.env:/app/.env  # Mount your environment file
      - ./custom-entrypoint.sh:/app/custom-entrypoint.sh
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
      - _PIP_ADDITIONAL_REQUIREMENTS=
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  scheduler:
    image: etl-app
    container_name: etl-scheduler
    restart: unless-stopped
    init: true
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./.env:/app/.env  # Mount your environment file
      - ./custom-entrypoint.sh:/app/custom-entrypoint.sh
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _PIP_ADDITIONAL_REQUIREMENTS=
    command: scheduler

networks:
  default:
    name: etl-network
    external: false